[theme]
base = "light"
primaryColor = "#111111"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f8"
textColor = "#333333"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
